name: Cache Workflow

on:
  push:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache-demo
          key: cache-860ebe2

      - name: prime-cache-860ebe2
        run: |
          echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
          mkdir -p ~/.cache-demo
          echo "cached-data" > ~/.cache-demo/file.txt
